#!/usr/bin/env node
// Local encrypted Firestore data export. Never deletes, writes or mutates Firebase.
import { applicationDefault } from 'firebase-admin/app';
import { stdin, stderr, stdout } from 'node:process';
import * as readline from 'node:readline';
import { lstat, mkdir } from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  makeFirestoreReader,
  verifyEncryptedFirestoreBackup,
  writeEncryptedFirestoreBackup,
} from './src/local_firestore_backup.js';
import { assertSafeTarget } from './src/safety.js';

const PROJECT = 'rokterbadhon-b247b';
const OPERATOR_ROOT = dirname(fileURLToPath(import.meta.url));
const BACKUP_DIR = join(OPERATOR_ROOT, '.local', 'backups');

function parseFlags(tokens) {
  if (tokens.length % 2 !== 0) throw new Error('Use --name value pairs.');
  const options = {};
  for (let i = 0; i < tokens.length; i += 2) {
    const key = tokens[i];
    if (!key.startsWith('--') || !tokens[i + 1]) {
      throw new Error('Use --name value pairs.');
    }
    if (options[key.slice(2)] !== undefined) {
      throw new Error('Repeated command option.');
    }
    options[key.slice(2)] = tokens[i + 1];
  }
  return options;
}

// TTY raw mode suppresses echo: neither typing nor passphrase enters shell history.
readline.emitKeypressEvents(stdin);
async function secretPrompt(label) {
  if (!stdin.isTTY || !stderr.isTTY || typeof stdin.setRawMode !== 'function') {
    throw new Error('Run in an interactive PowerShell/VS Code terminal.');
  }
  stderr.write(label);
  return new Promise((resolveSecret, rejectSecret) => {
    let value = '';
    const finish = (error) => {
      stdin.off('keypress', onKey);
      stdin.setRawMode(false);
      stdin.pause();
      stderr.write('\n');
      if (error) rejectSecret(error);
      else resolveSecret(value);
    };
    const onKey = (character, key) => {
      if (key?.name === 'return' || key?.name === 'enter') return finish();
      if (key?.ctrl && key?.name === 'c') {
        return finish(new Error('Backup password entry cancelled.'));
      }
      if (key?.name === 'backspace') {
        value = value.slice(0, -1);
        return;
      }
      if (!key?.ctrl && !key?.meta && character &&
          !/[\x00-\x1f\x7f]/.test(character)) {
        value += character;
      }
    };
    stdin.setRawMode(true);
    stdin.resume();
    stdin.on('keypress', onKey);
  });
}

function requireSafeTarget(options) {
  if (options['project-id'] !== PROJECT ||
      options['confirm-project-id'] !== PROJECT) {
    throw new Error('Expected both explicit matching Firebase project IDs.');
  }
  assertSafeTarget({
    projectId: PROJECT,
    firestoreEmulatorHost: process.env.FIRESTORE_EMULATOR_HOST,
    authEmulatorHost: process.env.FIREBASE_AUTH_EMULATOR_HOST,
    mode: 'provision',
    allowProduction: true,
    confirmedProjectId: PROJECT,
  });
}

function permittedBackupPath(name) {
  // Only one archive file immediately inside the ignored local backup folder.
  if (name !== basename(name) || !/^firestore-rokterbadhon-b247b-[0-9TZ]+\.rbfsenc$/.test(name)) {
    throw new Error('Verify a backup filename generated by this tool.');
  }
  return resolve(BACKUP_DIR, name);
}

function safeFailure(error) {
  const message = typeof error?.message === 'string' ? error.message : '';
  const allowed = [
    'Use --', 'Repeated command', 'Expected both', 'Backup password',
    'Run in an interactive', 'Backup destination', 'Backup restricted',
    'Firestore REST read failed (HTTP ', 'Firestore read could not reach',
    'Firestore returned', 'Unable to obtain Firebase', 'Unexpected Firestore',
    'Invalid Firestore', 'Invalid backup', 'Backup archive', 'Backup header',
    'Backup manifest', 'Backup contents', 'Backup contains', 'Local post-write',
    'Archive', 'Trailing records', 'Backup is', 'Verify a backup',
  ];
  if (allowed.some((prefix) => message.startsWith(prefix))) {
    return message.replace(/[\r\n]/g, ' ').slice(0, 230);
  }
  if (error?.code === 'EEXIST') return 'Output already exists; no file was replaced.';
  if (error?.code === 'ENOSPC') return 'Not enough disk space.';
  if (error?.code === 'EACCES' || error?.code === 'EPERM') return 'Local file permission denied.';
  return 'Read, credential, or archive verification error. No Firestore write was attempted.';
}

async function main() {
  const options = parseFlags(process.argv.slice(2));
  requireSafeTarget(options);
  const verifying = options.verify !== undefined;
  if (verifying && options.run !== undefined) throw new Error('Use --run or --verify, not both.');
  if (!verifying && options.run !== 'true') throw new Error('Use --run true to start the backup.');
  await mkdir(BACKUP_DIR, { recursive: true, mode: 0o700 });
  if (verifying) {
    const file = permittedBackupPath(options.verify);
    const details = await lstat(file);
    if (!details.isFile() || details.isSymbolicLink()) {
      throw new Error('Invalid backup archive file.');
    }
    const passphrase = await secretPrompt('Backup passphrase (hidden): ');
    const result = await verifyEncryptedFirestoreBackup({
      file, passphrase, expectedProjectId: PROJECT,
    });
    stdout.write(JSON.stringify({ file, ...result }, null, 2) + '\n');
    return;
  }
  const passphrase = await secretPrompt('Create backup passphrase (16+ characters, hidden): ');
  if (passphrase.length < 16) throw new Error('Backup password must contain at least 16 characters.');
  const confirm = await secretPrompt('Confirm backup passphrase (hidden): ');
  if (passphrase !== confirm) throw new Error('Backup password confirmation did not match.');

  const stamp = new Date().toISOString().replace(/[-:.]/g, '').replace(/\.\d{3}/, '');
  const file = join(BACKUP_DIR, 'firestore-' + PROJECT + '-' + stamp + '.rbfsenc');
  const credential = applicationDefault();
  const request = makeFirestoreReader({
    getAccessToken: async () => (await credential.getAccessToken()).access_token,
  });
  stdout.write('Read-only Firestore export started. All data is encrypted before writing to disk.\n');
  const result = await writeEncryptedFirestoreBackup({
    projectId: PROJECT, destination: file, passphrase, request,
    onProgress: ({ documentCount }) => {
      stdout.write('Read ' + documentCount + ' Firestore documents...\n');
    },
  });
  stdout.write(JSON.stringify(result, null, 2) + '\n');
  stdout.write('Keep the password offline. Without it the backup cannot be decrypted.\n');
  stdout.write('This backup does not include Firebase Authentication, Storage, or deployed Rules/Indexes.\n');
}

main().catch((error) => {
  stderr.write('Local Firestore backup failed: ' + safeFailure(error) + '\n');
  process.exitCode = 1;
});
