// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMo0jx9nvfb45CAvr79fNeOZCkXwMDKA8',
    appId: '1:941165503580:android:836f342d5b03c84cba7299',
    messagingSenderId: '941165503580',
    projectId: 'rokterbadhon-b247b',
    storageBucket: 'rokterbadhon-b247b.firebasestorage.app',
  );

  // The existing Firebase project exposes the standard Firebase Auth Web
  // domain, and its public client configuration is the same project as the
  // Android app above. No service-account credential or Storage dependency is
  // included here. Keep this as a separate platform entry so Android remains
  // driven by google-services.json.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMo0jx9nvfb45CAvr79fNeOZCkXwMDKA8',
    appId: '1:941165503580:android:836f342d5b03c84cba7299',
    messagingSenderId: '941165503580',
    projectId: 'rokterbadhon-b247b',
    authDomain: 'rokterbadhon-b247b.firebaseapp.com',
    storageBucket: 'rokterbadhon-b247b.firebasestorage.app',
  );
}
